---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - freqtrade.io
  resources:
  - frequis
  - strategies
  - tradebotconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - freqtrade.io
  resources:
  - frequis/status
  - strategies/status
  - tradebotconfigs/status
  - tradebots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - freqtrade.io
  resources:
  - tradebots
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - freqtrade.io
  resources:
  - tradebots/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - update
  - watch
