//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/api/networking/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIConfig) DeepCopyInto(out *AIConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.WriteMetricsToDisk != nil {
		in, out := &in.WriteMetricsToDisk, &out.WriteMetricsToDisk
		*out = new(bool)
		**out = **in
	}
	if in.PurgeOldModels != nil {
		in, out := &in.PurgeOldModels, &out.PurgeOldModels
		*out = new(int)
		**out = **in
	}
	if in.ConvWidth != nil {
		in, out := &in.ConvWidth, &out.ConvWidth
		*out = new(int)
		**out = **in
	}
	if in.TrainPeriodDays != nil {
		in, out := &in.TrainPeriodDays, &out.TrainPeriodDays
		*out = new(int)
		**out = **in
	}
	if in.BacktestPeriodDays != nil {
		in, out := &in.BacktestPeriodDays, &out.BacktestPeriodDays
		*out = new(int)
		**out = **in
	}
	if in.LiveRetrainHours != nil {
		in, out := &in.LiveRetrainHours, &out.LiveRetrainHours
		*out = new(int)
		**out = **in
	}
	if in.ExpirationHours != nil {
		in, out := &in.ExpirationHours, &out.ExpirationHours
		*out = new(int)
		**out = **in
	}
	if in.SaveBacktestModels != nil {
		in, out := &in.SaveBacktestModels, &out.SaveBacktestModels
		*out = new(bool)
		**out = **in
	}
	if in.FitLivePredictionsCandles != nil {
		in, out := &in.FitLivePredictionsCandles, &out.FitLivePredictionsCandles
		*out = new(int)
		**out = **in
	}
	if in.DataKitchenThreadCount != nil {
		in, out := &in.DataKitchenThreadCount, &out.DataKitchenThreadCount
		*out = new(int)
		**out = **in
	}
	if in.ActivateTensorboard != nil {
		in, out := &in.ActivateTensorboard, &out.ActivateTensorboard
		*out = new(bool)
		**out = **in
	}
	if in.WaitForTrainingIterationOnReload != nil {
		in, out := &in.WaitForTrainingIterationOnReload, &out.WaitForTrainingIterationOnReload
		*out = new(bool)
		**out = **in
	}
	if in.ContinueLearning != nil {
		in, out := &in.ContinueLearning, &out.ContinueLearning
		*out = new(bool)
		**out = **in
	}
	if in.Keras != nil {
		in, out := &in.Keras, &out.Keras
		*out = new(bool)
		**out = **in
	}
	if in.FeatureParameters != nil {
		in, out := &in.FeatureParameters, &out.FeatureParameters
		*out = new(FeatureParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.DataSplitParameters != nil {
		in, out := &in.DataSplitParameters, &out.DataSplitParameters
		*out = new(DataSplitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelTrainingParameters != nil {
		in, out := &in.ModelTrainingParameters, &out.ModelTrainingParameters
		*out = new(ModelTrainingParameters)
		**out = **in
	}
	if in.RLConfig != nil {
		in, out := &in.RLConfig, &out.RLConfig
		*out = new(RLConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIConfig.
func (in *AIConfig) DeepCopy() *AIConfig {
	if in == nil {
		return nil
	}
	out := new(AIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerConfig) DeepCopyInto(out *APIServerConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = new(int)
		**out = **in
	}
	if in.EnableOpenAPI != nil {
		in, out := &in.EnableOpenAPI, &out.EnableOpenAPI
		*out = new(bool)
		**out = **in
	}
	if in.CORSOrigins != nil {
		in, out := &in.CORSOrigins, &out.CORSOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerConfig.
func (in *APIServerConfig) DeepCopy() *APIServerConfig {
	if in == nil {
		return nil
	}
	out := new(APIServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedConfig) DeepCopyInto(out *AdvancedConfig) {
	*out = *in
	if in.TradableBalanceRatio != nil {
		in, out := &in.TradableBalanceRatio, &out.TradableBalanceRatio
		*out = new(float64)
		**out = **in
	}
	if in.CancelOpenOrdersOnExit != nil {
		in, out := &in.CancelOpenOrdersOnExit, &out.CancelOpenOrdersOnExit
		*out = new(bool)
		**out = **in
	}
	if in.ForceEntryEnable != nil {
		in, out := &in.ForceEntryEnable, &out.ForceEntryEnable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedConfig.
func (in *AdvancedConfig) DeepCopy() *AdvancedConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotConfig) DeepCopyInto(out *BotConfig) {
	*out = *in
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.DryRunWallet != nil {
		in, out := &in.DryRunWallet, &out.DryRunWallet
		*out = new(float64)
		**out = **in
	}
	if in.MaxOpenTrades != nil {
		in, out := &in.MaxOpenTrades, &out.MaxOpenTrades
		*out = new(int)
		**out = **in
	}
	if in.DisableParamExport != nil {
		in, out := &in.DisableParamExport, &out.DisableParamExport
		*out = new(bool)
		**out = **in
	}
	if in.DisableDataframeChecks != nil {
		in, out := &in.DisableDataframeChecks, &out.DisableDataframeChecks
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotConfig.
func (in *BotConfig) DeepCopy() *BotConfig {
	if in == nil {
		return nil
	}
	out := new(BotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataCacheSpec) DeepCopyInto(out *DataCacheSpec) {
	*out = *in
	if in.DownloadArgs != nil {
		in, out := &in.DownloadArgs, &out.DownloadArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataCacheSpec.
func (in *DataCacheSpec) DeepCopy() *DataCacheSpec {
	if in == nil {
		return nil
	}
	out := new(DataCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConfig) DeepCopyInto(out *DataConfig) {
	*out = *in
	if in.NewPairsDaysAgo != nil {
		in, out := &in.NewPairsDaysAgo, &out.NewPairsDaysAgo
		*out = new(int)
		**out = **in
	}
	if in.DownloadTrades != nil {
		in, out := &in.DownloadTrades, &out.DownloadTrades
		*out = new(bool)
		**out = **in
	}
	if in.MaxEntryPositionAdjustment != nil {
		in, out := &in.MaxEntryPositionAdjustment, &out.MaxEntryPositionAdjustment
		*out = new(float64)
		**out = **in
	}
	if in.AvailableCapital != nil {
		in, out := &in.AvailableCapital, &out.AvailableCapital
		*out = new(float64)
		**out = **in
	}
	if in.AmendLastStakeAmount != nil {
		in, out := &in.AmendLastStakeAmount, &out.AmendLastStakeAmount
		*out = new(bool)
		**out = **in
	}
	if in.LastStakeAmountMinRatio != nil {
		in, out := &in.LastStakeAmountMinRatio, &out.LastStakeAmountMinRatio
		*out = new(float64)
		**out = **in
	}
	if in.ProcessOnlyNewCandles != nil {
		in, out := &in.ProcessOnlyNewCandles, &out.ProcessOnlyNewCandles
		*out = new(bool)
		**out = **in
	}
	if in.AmountReservePercent != nil {
		in, out := &in.AmountReservePercent, &out.AmountReservePercent
		*out = new(float64)
		**out = **in
	}
	if in.ReduceDfFootprint != nil {
		in, out := &in.ReduceDfFootprint, &out.ReduceDfFootprint
		*out = new(bool)
		**out = **in
	}
	if in.CustomPriceMaxDistanceRatio != nil {
		in, out := &in.CustomPriceMaxDistanceRatio, &out.CustomPriceMaxDistanceRatio
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConfig.
func (in *DataConfig) DeepCopy() *DataConfig {
	if in == nil {
		return nil
	}
	out := new(DataConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSplitParameters) DeepCopyInto(out *DataSplitParameters) {
	*out = *in
	if in.TestSize != nil {
		in, out := &in.TestSize, &out.TestSize
		*out = new(float64)
		**out = **in
	}
	if in.RandomState != nil {
		in, out := &in.RandomState, &out.RandomState
		*out = new(int)
		**out = **in
	}
	if in.Shuffle != nil {
		in, out := &in.Shuffle, &out.Shuffle
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSplitParameters.
func (in *DataSplitParameters) DeepCopy() *DataSplitParameters {
	if in == nil {
		return nil
	}
	out := new(DataSplitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExchangeSpec) DeepCopyInto(out *ExchangeSpec) {
	*out = *in
	in.CcxtConfig.DeepCopyInto(&out.CcxtConfig)
	in.CcxtAsyncConfig.DeepCopyInto(&out.CcxtAsyncConfig)
	in.CcxtSyncConfig.DeepCopyInto(&out.CcxtSyncConfig)
	if in.Whitelist != nil {
		in, out := &in.Whitelist, &out.Whitelist
		*out = new(PairListSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Blacklist != nil {
		in, out := &in.Blacklist, &out.Blacklist
		*out = new(PairListSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LogResponses != nil {
		in, out := &in.LogResponses, &out.LogResponses
		*out = new(bool)
		**out = **in
	}
	if in.EnableWS != nil {
		in, out := &in.EnableWS, &out.EnableWS
		*out = new(bool)
		**out = **in
	}
	if in.UnkownFeeRate != nil {
		in, out := &in.UnkownFeeRate, &out.UnkownFeeRate
		*out = new(bool)
		**out = **in
	}
	if in.OutdatedOffset != nil {
		in, out := &in.OutdatedOffset, &out.OutdatedOffset
		*out = new(int)
		**out = **in
	}
	if in.MarketRefreshInterval != nil {
		in, out := &in.MarketRefreshInterval, &out.MarketRefreshInterval
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExchangeSpec.
func (in *ExchangeSpec) DeepCopy() *ExchangeSpec {
	if in == nil {
		return nil
	}
	out := new(ExchangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExperimentalConfig) DeepCopyInto(out *ExperimentalConfig) {
	*out = *in
	if in.BlockBadExchanges != nil {
		in, out := &in.BlockBadExchanges, &out.BlockBadExchanges
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExperimentalConfig.
func (in *ExperimentalConfig) DeepCopy() *ExperimentalConfig {
	if in == nil {
		return nil
	}
	out := new(ExperimentalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FUAppConfig) DeepCopyInto(out *FUAppConfig) {
	*out = *in
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(FUPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceSpec != nil {
		in, out := &in.ServiceSpec, &out.ServiceSpec
		*out = new(FUServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressSpec != nil {
		in, out := &in.IngressSpec, &out.IngressSpec
		*out = new(FUIngressSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FUAppConfig.
func (in *FUAppConfig) DeepCopy() *FUAppConfig {
	if in == nil {
		return nil
	}
	out := new(FUAppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FUIngressSpec) DeepCopyInto(out *FUIngressSpec) {
	*out = *in
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]v1.IngressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]v1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultBackend != nil {
		in, out := &in.DefaultBackend, &out.DefaultBackend
		*out = new(v1.IngressBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FUIngressSpec.
func (in *FUIngressSpec) DeepCopy() *FUIngressSpec {
	if in == nil {
		return nil
	}
	out := new(FUIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FUPodSpec) DeepCopyInto(out *FUPodSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.AntiAffinity != nil {
		in, out := &in.AntiAffinity, &out.AntiAffinity
		*out = new(corev1.PodAntiAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FUPodSpec.
func (in *FUPodSpec) DeepCopy() *FUPodSpec {
	if in == nil {
		return nil
	}
	out := new(FUPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FUServiceSpec) DeepCopyInto(out *FUServiceSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]corev1.ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LoadBalancerSourceRanges != nil {
		in, out := &in.LoadBalancerSourceRanges, &out.LoadBalancerSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FUServiceSpec.
func (in *FUServiceSpec) DeepCopy() *FUServiceSpec {
	if in == nil {
		return nil
	}
	out := new(FUServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureParameters) DeepCopyInto(out *FeatureParameters) {
	*out = *in
	if in.IncludeCorrPairlist != nil {
		in, out := &in.IncludeCorrPairlist, &out.IncludeCorrPairlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeTimeframes != nil {
		in, out := &in.IncludeTimeframes, &out.IncludeTimeframes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelPeriodCandles != nil {
		in, out := &in.LabelPeriodCandles, &out.LabelPeriodCandles
		*out = new(int)
		**out = **in
	}
	if in.IncludeShiftedCandles != nil {
		in, out := &in.IncludeShiftedCandles, &out.IncludeShiftedCandles
		*out = new(int)
		**out = **in
	}
	if in.DIThreshold != nil {
		in, out := &in.DIThreshold, &out.DIThreshold
		*out = new(float64)
		**out = **in
	}
	if in.WeightFactor != nil {
		in, out := &in.WeightFactor, &out.WeightFactor
		*out = new(float64)
		**out = **in
	}
	if in.PrincipalComponentAnalysis != nil {
		in, out := &in.PrincipalComponentAnalysis, &out.PrincipalComponentAnalysis
		*out = new(bool)
		**out = **in
	}
	if in.IndicatorPeriodsCandles != nil {
		in, out := &in.IndicatorPeriodsCandles, &out.IndicatorPeriodsCandles
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.UseSVMToRemoveOutliers != nil {
		in, out := &in.UseSVMToRemoveOutliers, &out.UseSVMToRemoveOutliers
		*out = new(bool)
		**out = **in
	}
	if in.PlotFeatureImportances != nil {
		in, out := &in.PlotFeatureImportances, &out.PlotFeatureImportances
		*out = new(int)
		**out = **in
	}
	if in.SVMParams != nil {
		in, out := &in.SVMParams, &out.SVMParams
		*out = new(SVMParams)
		(*in).DeepCopyInto(*out)
	}
	if in.ShuffleAfterSplit != nil {
		in, out := &in.ShuffleAfterSplit, &out.ShuffleAfterSplit
		*out = new(bool)
		**out = **in
	}
	if in.BufferTrainDataCandles != nil {
		in, out := &in.BufferTrainDataCandles, &out.BufferTrainDataCandles
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureParameters.
func (in *FeatureParameters) DeepCopy() *FeatureParameters {
	if in == nil {
		return nil
	}
	out := new(FeatureParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flow) DeepCopyInto(out *Flow) {
	*out = *in
	if in.CacheSize != nil {
		in, out := &in.CacheSize, &out.CacheSize
		*out = new(int)
		**out = **in
	}
	if in.MaxCandles != nil {
		in, out := &in.MaxCandles, &out.MaxCandles
		*out = new(int)
		**out = **in
	}
	if in.Scale != nil {
		in, out := &in.Scale, &out.Scale
		*out = new(float64)
		**out = **in
	}
	if in.StackedImbalanceRange != nil {
		in, out := &in.StackedImbalanceRange, &out.StackedImbalanceRange
		*out = new(int)
		**out = **in
	}
	if in.ImbalanceVolume != nil {
		in, out := &in.ImbalanceVolume, &out.ImbalanceVolume
		*out = new(int)
		**out = **in
	}
	if in.ImbalanceRatio != nil {
		in, out := &in.ImbalanceRatio, &out.ImbalanceRatio
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Flow.
func (in *Flow) DeepCopy() *Flow {
	if in == nil {
		return nil
	}
	out := new(Flow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreqUI) DeepCopyInto(out *FreqUI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreqUI.
func (in *FreqUI) DeepCopy() *FreqUI {
	if in == nil {
		return nil
	}
	out := new(FreqUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FreqUI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreqUIList) DeepCopyInto(out *FreqUIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FreqUI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreqUIList.
func (in *FreqUIList) DeepCopy() *FreqUIList {
	if in == nil {
		return nil
	}
	out := new(FreqUIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FreqUIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreqUISpec) DeepCopyInto(out *FreqUISpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]v1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IngressAnnotations != nil {
		in, out := &in.IngressAnnotations, &out.IngressAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.App != nil {
		in, out := &in.App, &out.App
		*out = new(FUAppConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TradeBotRefs != nil {
		in, out := &in.TradeBotRefs, &out.TradeBotRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreqUISpec.
func (in *FreqUISpec) DeepCopy() *FreqUISpec {
	if in == nil {
		return nil
	}
	out := new(FreqUISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreqUIStatus) DeepCopyInto(out *FreqUIStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreqUIStatus.
func (in *FreqUIStatus) DeepCopy() *FreqUIStatus {
	if in == nil {
		return nil
	}
	out := new(FreqUIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalsConfig) DeepCopyInto(out *InternalsConfig) {
	*out = *in
	if in.ProcessThrottleSecs != nil {
		in, out := &in.ProcessThrottleSecs, &out.ProcessThrottleSecs
		*out = new(int)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(int)
		**out = **in
	}
	if in.SdNotify != nil {
		in, out := &in.SdNotify, &out.SdNotify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalsConfig.
func (in *InternalsConfig) DeepCopy() *InternalsConfig {
	if in == nil {
		return nil
	}
	out := new(InternalsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRewardParameters) DeepCopyInto(out *ModelRewardParameters) {
	*out = *in
	if in.RR != nil {
		in, out := &in.RR, &out.RR
		*out = new(float64)
		**out = **in
	}
	if in.ProfitAim != nil {
		in, out := &in.ProfitAim, &out.ProfitAim
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRewardParameters.
func (in *ModelRewardParameters) DeepCopy() *ModelRewardParameters {
	if in == nil {
		return nil
	}
	out := new(ModelRewardParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelTrainingParameters) DeepCopyInto(out *ModelTrainingParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelTrainingParameters.
func (in *ModelTrainingParameters) DeepCopy() *ModelTrainingParameters {
	if in == nil {
		return nil
	}
	out := new(ModelTrainingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationDiscord) DeepCopyInto(out *NotificationDiscord) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExitFill != nil {
		in, out := &in.ExitFill, &out.ExitFill
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.EntryFill != nil {
		in, out := &in.EntryFill, &out.EntryFill
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationDiscord.
func (in *NotificationDiscord) DeepCopy() *NotificationDiscord {
	if in == nil {
		return nil
	}
	out := new(NotificationDiscord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSpec) DeepCopyInto(out *NotificationSpec) {
	*out = *in
	if in.Telegram != nil {
		in, out := &in.Telegram, &out.Telegram
		*out = new(NotificationTelegram)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(NotificationWebhook)
		(*in).DeepCopyInto(*out)
	}
	if in.Discord != nil {
		in, out := &in.Discord, &out.Discord
		*out = new(NotificationDiscord)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSpec.
func (in *NotificationSpec) DeepCopy() *NotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTelegram) DeepCopyInto(out *NotificationTelegram) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.BalanceDustLevel != nil {
		in, out := &in.BalanceDustLevel, &out.BalanceDustLevel
		*out = new(float64)
		**out = **in
	}
	if in.Reload != nil {
		in, out := &in.Reload, &out.Reload
		*out = new(bool)
		**out = **in
	}
	if in.AllowCustomMessages != nil {
		in, out := &in.AllowCustomMessages, &out.AllowCustomMessages
		*out = new(bool)
		**out = **in
	}
	if in.AuthorizedUsers != nil {
		in, out := &in.AuthorizedUsers, &out.AuthorizedUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(NotificationTelegramSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTelegram.
func (in *NotificationTelegram) DeepCopy() *NotificationTelegram {
	if in == nil {
		return nil
	}
	out := new(NotificationTelegram)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationTelegramSettings) DeepCopyInto(out *NotificationTelegramSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationTelegramSettings.
func (in *NotificationTelegramSettings) DeepCopy() *NotificationTelegramSettings {
	if in == nil {
		return nil
	}
	out := new(NotificationTelegramSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationWebhook) DeepCopyInto(out *NotificationWebhook) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AllowCustomMessages != nil {
		in, out := &in.AllowCustomMessages, &out.AllowCustomMessages
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationWebhook.
func (in *NotificationWebhook) DeepCopy() *NotificationWebhook {
	if in == nil {
		return nil
	}
	out := new(NotificationWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrderSpec) DeepCopyInto(out *OrderSpec) {
	*out = *in
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = new(Types)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeInForce != nil {
		in, out := &in.TimeInForce, &out.TimeInForce
		*out = new(TimeInForce)
		**out = **in
	}
	if in.Flow != nil {
		in, out := &in.Flow, &out.Flow
		*out = new(Flow)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrderSpec.
func (in *OrderSpec) DeepCopy() *OrderSpec {
	if in == nil {
		return nil
	}
	out := new(OrderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCSpec) DeepCopyInto(out *PVCSpec) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCSpec.
func (in *PVCSpec) DeepCopy() *PVCSpec {
	if in == nil {
		return nil
	}
	out := new(PVCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PairListSpec) DeepCopyInto(out *PairListSpec) {
	*out = *in
	if in.Pairs != nil {
		in, out := &in.Pairs, &out.Pairs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PairListSpec.
func (in *PairListSpec) DeepCopy() *PairListSpec {
	if in == nil {
		return nil
	}
	out := new(PairListSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PairlistConfig) DeepCopyInto(out *PairlistConfig) {
	*out = *in
	if in.NumberAssets != nil {
		in, out := &in.NumberAssets, &out.NumberAssets
		*out = new(int)
		**out = **in
	}
	if in.RefreshPeriod != nil {
		in, out := &in.RefreshPeriod, &out.RefreshPeriod
		*out = new(int64)
		**out = **in
	}
	if in.LookbackPeriod != nil {
		in, out := &in.LookbackPeriod, &out.LookbackPeriod
		*out = new(int)
		**out = **in
	}
	if in.LookbackDays != nil {
		in, out := &in.LookbackDays, &out.LookbackDays
		*out = new(int)
		**out = **in
	}
	if in.MinChangeRate != nil {
		in, out := &in.MinChangeRate, &out.MinChangeRate
		*out = new(float64)
		**out = **in
	}
	if in.KeepPairlistOnFailure != nil {
		in, out := &in.KeepPairlistOnFailure, &out.KeepPairlistOnFailure
		*out = new(bool)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(int)
		**out = **in
	}
	if in.MaxRank != nil {
		in, out := &in.MaxRank, &out.MaxRank
		*out = new(int)
		**out = **in
	}
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinDaysListed != nil {
		in, out := &in.MinDaysListed, &out.MinDaysListed
		*out = new(int)
		**out = **in
	}
	if in.MaxDaysListed != nil {
		in, out := &in.MaxDaysListed, &out.MaxDaysListed
		*out = new(int)
		**out = **in
	}
	if in.MinPrice != nil {
		in, out := &in.MinPrice, &out.MinPrice
		*out = new(float64)
		**out = **in
	}
	if in.MaxPrice != nil {
		in, out := &in.MaxPrice, &out.MaxPrice
		*out = new(float64)
		**out = **in
	}
	if in.MaxSpreadRatio != nil {
		in, out := &in.MaxSpreadRatio, &out.MaxSpreadRatio
		*out = new(float64)
		**out = **in
	}
	if in.LookbackDaysRange != nil {
		in, out := &in.LookbackDaysRange, &out.LookbackDaysRange
		*out = new(int)
		**out = **in
	}
	if in.MinRateOfChange != nil {
		in, out := &in.MinRateOfChange, &out.MinRateOfChange
		*out = new(float64)
		**out = **in
	}
	if in.MaxRateOfChange != nil {
		in, out := &in.MaxRateOfChange, &out.MaxRateOfChange
		*out = new(float64)
		**out = **in
	}
	if in.LookbackDaysVolatility != nil {
		in, out := &in.LookbackDaysVolatility, &out.LookbackDaysVolatility
		*out = new(int)
		**out = **in
	}
	if in.MinVolatility != nil {
		in, out := &in.MinVolatility, &out.MinVolatility
		*out = new(float64)
		**out = **in
	}
	if in.MaxVolatility != nil {
		in, out := &in.MaxVolatility, &out.MaxVolatility
		*out = new(float64)
		**out = **in
	}
	if in.Offset != nil {
		in, out := &in.Offset, &out.Offset
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PairlistConfig.
func (in *PairlistConfig) DeepCopy() *PairlistConfig {
	if in == nil {
		return nil
	}
	out := new(PairlistConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PairlistMethodsSpec) DeepCopyInto(out *PairlistMethodsSpec) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]PairlistConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PairlistMethodsSpec.
func (in *PairlistMethodsSpec) DeepCopy() *PairlistMethodsSpec {
	if in == nil {
		return nil
	}
	out := new(PairlistMethodsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpec) DeepCopyInto(out *PodSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.AntiAffinity != nil {
		in, out := &in.AntiAffinity, &out.AntiAffinity
		*out = new(corev1.PodAntiAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSpec.
func (in *PodSpec) DeepCopy() *PodSpec {
	if in == nil {
		return nil
	}
	out := new(PodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricingCheckDepthOfMarket) DeepCopyInto(out *PricingCheckDepthOfMarket) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.BidsToAskDelta != nil {
		in, out := &in.BidsToAskDelta, &out.BidsToAskDelta
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricingCheckDepthOfMarket.
func (in *PricingCheckDepthOfMarket) DeepCopy() *PricingCheckDepthOfMarket {
	if in == nil {
		return nil
	}
	out := new(PricingCheckDepthOfMarket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricingSpec) DeepCopyInto(out *PricingSpec) {
	*out = *in
	if in.PriceLastBalance != nil {
		in, out := &in.PriceLastBalance, &out.PriceLastBalance
		*out = new(float64)
		**out = **in
	}
	if in.UseOrderBook != nil {
		in, out := &in.UseOrderBook, &out.UseOrderBook
		*out = new(bool)
		**out = **in
	}
	if in.OrderBookTop != nil {
		in, out := &in.OrderBookTop, &out.OrderBookTop
		*out = new(int)
		**out = **in
	}
	if in.CheckDepthOfMarket != nil {
		in, out := &in.CheckDepthOfMarket, &out.CheckDepthOfMarket
		*out = new(PricingCheckDepthOfMarket)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricingSpec.
func (in *PricingSpec) DeepCopy() *PricingSpec {
	if in == nil {
		return nil
	}
	out := new(PricingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RLConfig) DeepCopyInto(out *RLConfig) {
	*out = *in
	if in.DropOHLCFromFeatures != nil {
		in, out := &in.DropOHLCFromFeatures, &out.DropOHLCFromFeatures
		*out = new(bool)
		**out = **in
	}
	if in.TrainCycles != nil {
		in, out := &in.TrainCycles, &out.TrainCycles
		*out = new(int)
		**out = **in
	}
	if in.MaxTradeDurationCandles != nil {
		in, out := &in.MaxTradeDurationCandles, &out.MaxTradeDurationCandles
		*out = new(int)
		**out = **in
	}
	if in.AddStateInfo != nil {
		in, out := &in.AddStateInfo, &out.AddStateInfo
		*out = new(bool)
		**out = **in
	}
	if in.MaxTrainingDrawdownPct != nil {
		in, out := &in.MaxTrainingDrawdownPct, &out.MaxTrainingDrawdownPct
		*out = new(float64)
		**out = **in
	}
	if in.CPUCount != nil {
		in, out := &in.CPUCount, &out.CPUCount
		*out = new(int)
		**out = **in
	}
	if in.NetArch != nil {
		in, out := &in.NetArch, &out.NetArch
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.RandomizeStartingPosition != nil {
		in, out := &in.RandomizeStartingPosition, &out.RandomizeStartingPosition
		*out = new(bool)
		**out = **in
	}
	if in.ProgressBar != nil {
		in, out := &in.ProgressBar, &out.ProgressBar
		*out = new(bool)
		**out = **in
	}
	if in.ModelRewardParameters != nil {
		in, out := &in.ModelRewardParameters, &out.ModelRewardParameters
		*out = new(ModelRewardParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RLConfig.
func (in *RLConfig) DeepCopy() *RLConfig {
	if in == nil {
		return nil
	}
	out := new(RLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RiskManagementSpec) DeepCopyInto(out *RiskManagementSpec) {
	*out = *in
	if in.MinimalROI != nil {
		in, out := &in.MinimalROI, &out.MinimalROI
		*out = make(map[string]*float64, len(*in))
		for key, val := range *in {
			var outVal *float64
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(float64)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Stoploss != nil {
		in, out := &in.Stoploss, &out.Stoploss
		*out = new(float64)
		**out = **in
	}
	if in.TrailingStopPositive != nil {
		in, out := &in.TrailingStopPositive, &out.TrailingStopPositive
		*out = new(float64)
		**out = **in
	}
	if in.TrailingStopPositiveOffset != nil {
		in, out := &in.TrailingStopPositiveOffset, &out.TrailingStopPositiveOffset
		*out = new(float64)
		**out = **in
	}
	if in.ExitProfitOffset != nil {
		in, out := &in.ExitProfitOffset, &out.ExitProfitOffset
		*out = new(float64)
		**out = **in
	}
	if in.Fee != nil {
		in, out := &in.Fee, &out.Fee
		*out = new(float64)
		**out = **in
	}
	if in.IgnoreBuyingExpiredCandleAfter != nil {
		in, out := &in.IgnoreBuyingExpiredCandleAfter, &out.IgnoreBuyingExpiredCandleAfter
		*out = new(int)
		**out = **in
	}
	if in.MinimumTradeAmount != nil {
		in, out := &in.MinimumTradeAmount, &out.MinimumTradeAmount
		*out = new(int)
		**out = **in
	}
	if in.TargetedTradeAmount != nil {
		in, out := &in.TargetedTradeAmount, &out.TargetedTradeAmount
		*out = new(int)
		**out = **in
	}
	if in.StartupCandle != nil {
		in, out := &in.StartupCandle, &out.StartupCandle
		*out = new([]int)
		if **in != nil {
			in, out := *in, *out
			*out = make([]int, len(*in))
			copy(*out, *in)
		}
	}
	if in.LiquidationBuffer != nil {
		in, out := &in.LiquidationBuffer, &out.LiquidationBuffer
		*out = new(float64)
		**out = **in
	}
	if in.BacktestBreakdown != nil {
		in, out := &in.BacktestBreakdown, &out.BacktestBreakdown
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RiskManagementSpec.
func (in *RiskManagementSpec) DeepCopy() *RiskManagementSpec {
	if in == nil {
		return nil
	}
	out := new(RiskManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SVMParams) DeepCopyInto(out *SVMParams) {
	*out = *in
	if in.Shuffle != nil {
		in, out := &in.Shuffle, &out.Shuffle
		*out = new(bool)
		**out = **in
	}
	if in.Nu != nil {
		in, out := &in.Nu, &out.Nu
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SVMParams.
func (in *SVMParams) DeepCopy() *SVMParams {
	if in == nil {
		return nil
	}
	out := new(SVMParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]corev1.ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Strategy) DeepCopyInto(out *Strategy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Strategy.
func (in *Strategy) DeepCopy() *Strategy {
	if in == nil {
		return nil
	}
	out := new(Strategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Strategy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyList) DeepCopyInto(out *StrategyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Strategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyList.
func (in *StrategyList) DeepCopy() *StrategyList {
	if in == nil {
		return nil
	}
	out := new(StrategyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StrategyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategySpec) DeepCopyInto(out *StrategySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategySpec.
func (in *StrategySpec) DeepCopy() *StrategySpec {
	if in == nil {
		return nil
	}
	out := new(StrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyStatus) DeepCopyInto(out *StrategyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyStatus.
func (in *StrategyStatus) DeepCopy() *StrategyStatus {
	if in == nil {
		return nil
	}
	out := new(StrategyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TBAppConfig) DeepCopyInto(out *TBAppConfig) {
	*out = *in
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(PodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceSpec != nil {
		in, out := &in.ServiceSpec, &out.ServiceSpec
		*out = new(ServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PVCSpec != nil {
		in, out := &in.PVCSpec, &out.PVCSpec
		*out = new(PVCSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TBAppConfig.
func (in *TBAppConfig) DeepCopy() *TBAppConfig {
	if in == nil {
		return nil
	}
	out := new(TBAppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeInForce) DeepCopyInto(out *TimeInForce) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeInForce.
func (in *TimeInForce) DeepCopy() *TimeInForce {
	if in == nil {
		return nil
	}
	out := new(TimeInForce)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TradeBot) DeepCopyInto(out *TradeBot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TradeBot.
func (in *TradeBot) DeepCopy() *TradeBot {
	if in == nil {
		return nil
	}
	out := new(TradeBot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TradeBot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TradeBotConfig) DeepCopyInto(out *TradeBotConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TradeBotConfig.
func (in *TradeBotConfig) DeepCopy() *TradeBotConfig {
	if in == nil {
		return nil
	}
	out := new(TradeBotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TradeBotConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TradeBotConfigList) DeepCopyInto(out *TradeBotConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TradeBotConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TradeBotConfigList.
func (in *TradeBotConfigList) DeepCopy() *TradeBotConfigList {
	if in == nil {
		return nil
	}
	out := new(TradeBotConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TradeBotConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TradeBotConfigSpec) DeepCopyInto(out *TradeBotConfigSpec) {
	*out = *in
	if in.Bot != nil {
		in, out := &in.Bot, &out.Bot
		*out = new(BotConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(AIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(DataConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Advanced != nil {
		in, out := &in.Advanced, &out.Advanced
		*out = new(AdvancedConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(UnfilledTimeoutConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internals != nil {
		in, out := &in.Internals, &out.Internals
		*out = new(InternalsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Exchange != nil {
		in, out := &in.Exchange, &out.Exchange
		*out = new(ExchangeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pairlist != nil {
		in, out := &in.Pairlist, &out.Pairlist
		*out = new(PairListSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PairlistMethod != nil {
		in, out := &in.PairlistMethod, &out.PairlistMethod
		*out = new(PairlistMethodsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EntryPricing != nil {
		in, out := &in.EntryPricing, &out.EntryPricing
		*out = new(PricingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExitPricing != nil {
		in, out := &in.ExitPricing, &out.ExitPricing
		*out = new(PricingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(OrderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RiskManagement != nil {
		in, out := &in.RiskManagement, &out.RiskManagement
		*out = new(RiskManagementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Notification != nil {
		in, out := &in.Notification, &out.Notification
		*out = new(NotificationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.APIServer != nil {
		in, out := &in.APIServer, &out.APIServer
		*out = new(APIServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Experimental != nil {
		in, out := &in.Experimental, &out.Experimental
		*out = new(ExperimentalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TradeBotConfigSpec.
func (in *TradeBotConfigSpec) DeepCopy() *TradeBotConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TradeBotConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TradeBotConfigStatus) DeepCopyInto(out *TradeBotConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TradeBotConfigStatus.
func (in *TradeBotConfigStatus) DeepCopy() *TradeBotConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TradeBotConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TradeBotList) DeepCopyInto(out *TradeBotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TradeBot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TradeBotList.
func (in *TradeBotList) DeepCopy() *TradeBotList {
	if in == nil {
		return nil
	}
	out := new(TradeBotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TradeBotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TradeBotSpec) DeepCopyInto(out *TradeBotSpec) {
	*out = *in
	if in.FreqtradeArguments != nil {
		in, out := &in.FreqtradeArguments, &out.FreqtradeArguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.App != nil {
		in, out := &in.App, &out.App
		*out = new(TBAppConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(DataCacheSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TradeBotSpec.
func (in *TradeBotSpec) DeepCopy() *TradeBotSpec {
	if in == nil {
		return nil
	}
	out := new(TradeBotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TradeBotStatus) DeepCopyInto(out *TradeBotStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TradeBotStatus.
func (in *TradeBotStatus) DeepCopy() *TradeBotStatus {
	if in == nil {
		return nil
	}
	out := new(TradeBotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Types) DeepCopyInto(out *Types) {
	*out = *in
	if in.StoplossOnExchange != nil {
		in, out := &in.StoplossOnExchange, &out.StoplossOnExchange
		*out = new(bool)
		**out = **in
	}
	if in.StoplossOnExchangeInterval != nil {
		in, out := &in.StoplossOnExchangeInterval, &out.StoplossOnExchangeInterval
		*out = new(int)
		**out = **in
	}
	if in.StoplossOnExchangeLimitRatio != nil {
		in, out := &in.StoplossOnExchangeLimitRatio, &out.StoplossOnExchangeLimitRatio
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Types.
func (in *Types) DeepCopy() *Types {
	if in == nil {
		return nil
	}
	out := new(Types)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnfilledTimeoutConfig) DeepCopyInto(out *UnfilledTimeoutConfig) {
	*out = *in
	if in.Entry != nil {
		in, out := &in.Entry, &out.Entry
		*out = new(int)
		**out = **in
	}
	if in.Exit != nil {
		in, out := &in.Exit, &out.Exit
		*out = new(int)
		**out = **in
	}
	if in.ExitTimeoutCount != nil {
		in, out := &in.ExitTimeoutCount, &out.ExitTimeoutCount
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnfilledTimeoutConfig.
func (in *UnfilledTimeoutConfig) DeepCopy() *UnfilledTimeoutConfig {
	if in == nil {
		return nil
	}
	out := new(UnfilledTimeoutConfig)
	in.DeepCopyInto(out)
	return out
}
