apiVersion: freqtrade.io/v1alpha1
kind: FreqUI
metadata:
  name: freqtrade-ui
  namespace: freqtrade-example
spec:
  host: frequi.example.com
  tls:
    - hosts:
        - "frequi.example.com"
        - "*.frequi.example.com"
      secretName: frequi-example-tls
  ingressAnnotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  tradeBotRefs:
    - btc-trader