apiVersion: freqtrade.io/v1alpha1
kind: Notification
metadata:
  name: telegram-notifications
  namespace: freqtrade-example
spec:
  telegram:
    enabled: true
    secretRef: telegram-credentials
    balance_dust_level: 0.01
    reload: true
    chat_id: "your-chat-id"
