apiVersion: freqtrade.io/v1alpha1
kind: Notification
metadata:
  name: telegram-notifications
  namespace: freqtrade
spec:
  telegram:
    enabled: true
    secretRef: telegram-credentials
    balanceDustLevel: 0.01
    reload: true
    allowCustomMessages: true
  apiServer:
    enabled: true
    listenIpAddress: "0.0.0.0"
    listenPort: 8080
    verbosity: "info"
    secretRef: api-server-credentials