apiVersion: freqtrade.io/v1alpha1
kind: Order
metadata:
  name: default-order-types
  namespace: freqtrade-example
spec:
  types:
    entry: "limit"
    exit: "limit"
    emergency_exit: "market"
    force_entry: "market"
    force_exit: "market"
    stoploss: "market"
    stoploss_on_exchange: false
    stoploss_on_exchange_interval: 60
    stoploss_on_exchange_limit_ratio: 0.9
