apiVersion: freqtrade.io/v1alpha1
kind: Order
metadata:
  name: default-order-types
  namespace: freqtrade
spec:
  types:
    entry: "limit"
    exit: "limit"
    stoploss: "market"
    force_entry: "market"
    force_exit: "market"
    stoploss_on_exchange: false
    stoploss_on_exchange_interval: 60
