apiVersion: freqtrade.ark-sys.github.io/v1alpha1
kind: PairList
metadata:
  name: whitelist
spec:
  pairs:
    - BTC/USDT
    - ETH/USDT
---
apiVersion: freqtrade.ark-sys.github.io/v1alpha1
kind: PairList
metadata:
  name: blacklist
spec:
  pairs:
    - DOGE/USDT