apiVersion: freqtrade.io/v1alpha1
kind: Pricing
metadata:
  name: default-entry-pricing
  namespace: freqtrade
spec:
  price_side: "bid"
  use_order_book: false
  price_last_balance: false


---
apiVersion: freqtrade.io/v1alpha1
kind: Pricing
metadata:
  name: default-exit-pricing
  namespace: freqtrade
spec:
    price_side: "ask"
    use_order_book: false
    price_last_balance: false

