apiVersion: freqtrade.io/v1alpha1
kind: EntryPricing
metadata:
  name: default-entrypricing
  namespace: freqtrade
spec:
  priceSide: "bid"
  useOrderBook: false
---
apiVersion: freqtrade.io/v1alpha1
kind: ExitPricing
metadata:
  name: default-exitpricing
  namespace: freqtrade
spec:
  priceSide: "bid"
  useOrderBook: false