apiVersion: freqtrade.io/v1alpha1
kind: RiskManagement
metadata:
  name: default-risk
  namespace: freqtrade
spec:
  minimalRoi:
    "0": 0.1
    "10": 0.05
  stoploss: -0.2
  trailingStop: true
  trailingStopPositive: 0.01
  trailingStopPositiveOffset: 0.02
  trailingOnlyOffsetIsReached: true