apiVersion: freqtrade.io/v1alpha1
kind: TradeBot
metadata:
  name: btc-trader
  namespace: freqtrade-example
  annotations:
    freqtrade.io/preserve-data: "true"
spec:
  strategy: default-strategy

  config: btc-trader-config
  app:
    pvc:
      storageClassName: "longhorn"
      storageSize: "1Gi"

    pod:
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "100m"




