apiVersion: freqtrade.io/v1alpha1
kind: PairList
metadata:
  name: crypto-whitelist
  namespace: freqtrade-example
spec:
  pairs:
    - "BTC/USDT"
    - "ETH/USDT"
    - "XRP/USDT"
    - "LTC/USDT"
    - "BCH/USDT"
    - "ADA/USDT"
    - "DOT/USDT"
    - "LINK/USDT"
    - "XLM/USDT"
    - "SOL/USDT"
    - "AVAX/USDT"
    - "MATIC/USDT"

